# Generated by Django 3.0.7 on 2020-06-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(max_length=24)),
                ('student_id', models.IntegerField()),
                ('stream', models.CharField(max_length=10)),
                ('Date_of_suspension', models.DateField()),
                ('return_date', models.DateField()),
                ('timestamp', models.DateField(auto_now=True)),
                ('Reason_of_suspension', models.CharField(max_length=2000)),
                ('Teachers_sign', models.CharField(max_length=120)),
                ('Adm_No', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
