# Generated by Django 3.0.7 on 2020-06-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='students',
        ),
    ]
